-- FormaPlus schema: one database shared by all schools.
-- Every row carries school_id; RLS lets a user see only schools they belong to, filtered by role.
-- Foreign keys include school_id, so a row can never point at another school's data.
-- Amounts are whole units of the school's currency. Balances are derived (enrollment_balances), never stored.

create table schools (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'), -- subdomain: <slug>.formaplus.app
  custom_domain text unique,
  currency text not null default 'DA',
  created_at timestamptz not null default now()
);

create table teachers (
  id bigint generated by default as identity primary key,
  school_id bigint not null references schools(id) on delete cascade,
  full_name text not null,
  subject text,
  phone text,
  email text,
  hourly_rate integer not null default 2000 check (hourly_rate >= 0),
  contract text not null default 'Temps partiel' check (contract in ('Temps plein', 'Temps partiel', 'Vacataire')),
  color text not null default '#5B8DEF',
  created_at timestamptz not null default now(),
  unique (school_id, id)
);

create table school_members (
  school_id bigint not null references schools(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('director', 'secretaire', 'teacher')),
  teacher_id bigint, -- required for role 'teacher': links the login to their teacher record
  created_at timestamptz not null default now(),
  primary key (school_id, user_id),
  foreign key (school_id, teacher_id) references teachers(school_id, id) on delete set null (teacher_id),
  check (role <> 'teacher' or teacher_id is not null)
);
create index on school_members (user_id);

create table courses (
  id bigint generated by default as identity primary key,
  school_id bigint not null references schools(id) on delete cascade,
  name text not null,
  short_name text not null,
  duration text not null,
  price integer not null check (price >= 0),
  color text not null default '#5B8DEF',
  created_at timestamptz not null default now(),
  unique (school_id, id),
  unique (school_id, name)
);

create table groups (
  id bigint generated by default as identity primary key,
  school_id bigint not null references schools(id) on delete cascade,
  name text not null,
  course_id bigint,
  teacher_id bigint,
  room text,
  schedule text,
  days text[] not null default '{}',
  start_time time,
  capacity integer not null default 15 check (capacity > 0),
  status text not null default 'Ouvert' check (status in ('Ouvert', 'Complet', 'Annulé')),
  color text not null default '#5B8DEF',
  created_at timestamptz not null default now(),
  unique (school_id, id),
  foreign key (school_id, course_id) references courses(school_id, id) on delete set null (course_id),
  foreign key (school_id, teacher_id) references teachers(school_id, id) on delete set null (teacher_id)
);
create index on groups (school_id, teacher_id);

create table students (
  id bigint generated by default as identity primary key,
  school_id bigint not null references schools(id) on delete cascade,
  full_name text not null,
  phone text not null,
  email text,
  address text,
  dob date,
  source text,
  stage text not null default 'inscrit' check (stage in ('inscrit', 'encours', 'diplome', 'abandonne')),
  staff text,
  last_contact date,
  created_at timestamptz not null default now(),
  unique (school_id, id)
);
create index on students (school_id);

create table group_students (
  school_id bigint not null,
  group_id bigint not null,
  student_id bigint not null,
  primary key (group_id, student_id),
  foreign key (school_id, group_id) references groups(school_id, id) on delete cascade,
  foreign key (school_id, student_id) references students(school_id, id) on delete cascade
);

create table enrollments (
  id bigint generated by default as identity primary key,
  school_id bigint not null,
  student_id bigint not null,
  course_id bigint not null,
  group_id bigint,
  enrolled_on date not null default current_date,
  status text not null default 'Inscrit' check (status in ('Inscrit', 'En cours', 'Terminé', 'Abandonné')),
  total integer not null check (total >= 0),
  notes text,
  created_at timestamptz not null default now(),
  unique (school_id, id),
  foreign key (school_id, student_id) references students(school_id, id) on delete cascade,
  foreign key (school_id, course_id) references courses(school_id, id),
  foreign key (school_id, group_id) references groups(school_id, id) on delete set null (group_id)
);
create index on enrollments (school_id, student_id);

create table payments (
  id bigint generated by default as identity primary key,
  school_id bigint not null,
  enrollment_id bigint not null,
  amount integer not null check (amount > 0),
  paid_on date not null default current_date,
  method text not null check (method in ('Virement', 'Espèces', 'Chèque')),
  created_at timestamptz not null default now(),
  foreign key (school_id, enrollment_id) references enrollments(school_id, id) on delete cascade
);
create index on payments (school_id, enrollment_id);

create table attendance (
  school_id bigint not null,
  group_id bigint not null,
  student_id bigint not null,
  session_date date not null,
  status text not null check (status in ('P', 'A', 'L')),
  primary key (group_id, student_id, session_date),
  foreign key (school_id, group_id) references groups(school_id, id) on delete cascade,
  foreign key (school_id, student_id) references students(school_id, id) on delete cascade
);
create index on attendance (school_id, student_id);

create table student_documents (
  id bigint generated by default as identity primary key,
  school_id bigint not null,
  student_id bigint not null,
  type text not null,
  file_path text not null,
  status text not null default 'À vérifier' check (status in ('Validé', 'À vérifier')),
  created_at timestamptz not null default now(),
  foreign key (school_id, student_id) references students(school_id, id) on delete cascade
);
create index on student_documents (school_id, student_id);

create table student_notes (
  id bigint generated by default as identity primary key,
  school_id bigint not null,
  student_id bigint not null,
  body text not null check (length(trim(body)) > 0),
  author_id uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  foreign key (school_id, student_id) references students(school_id, id) on delete cascade
);
create index on student_notes (school_id, student_id);

create view enrollment_balances with (security_invoker = true) as
select
  e.id as enrollment_id,
  e.school_id,
  e.student_id,
  e.course_id,
  e.total,
  coalesce(sum(p.amount), 0)::integer as paid,
  greatest(e.total - coalesce(sum(p.amount), 0), 0)::integer as balance,
  case when coalesce(sum(p.amount), 0) >= e.total then 'Payé' else 'Partiel' end as payment_status
from enrollments e
left join payments p on p.enrollment_id = e.id
group by e.id;

-- ---------------------------------------------------------------------------
-- Access rules
--   director   : everything in their school
--   secretaire : students (+ enrollments, documents, notes), courses, groups, planning, attendance, payments;
--                teachers read-only (needed to show and assign group teachers)
--   teacher    : courses read-only; only the groups they teach; their own teacher record
-- Helpers live in a schema the API does not expose, and run as owner so policies on
-- school_members don't recurse.
-- ---------------------------------------------------------------------------

create schema private;
grant usage on schema private to authenticated;

create function private.has_role(p_school_id bigint, p_roles text[])
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.school_members m
    where m.school_id = p_school_id and m.user_id = auth.uid() and m.role = any (p_roles)
  );
$$;

create function private.my_teacher_id(p_school_id bigint)
returns bigint language sql stable security definer set search_path = '' as $$
  select m.teacher_id from public.school_members m
  where m.school_id = p_school_id and m.user_id = auth.uid() and m.role = 'teacher';
$$;

grant execute on function private.has_role(bigint, text[]), private.my_teacher_id(bigint) to authenticated;

alter table schools enable row level security;
create policy "members read their school" on schools for select to authenticated
  using (private.has_role(id, '{director,secretaire,teacher}'));
create policy "director updates school" on schools for update to authenticated
  using (private.has_role(id, '{director}')) with check (private.has_role(id, '{director}'));
-- No insert/delete policy: new schools are created by the platform (service role), not from the app.

alter table school_members enable row level security;
create policy "see own membership" on school_members for select to authenticated
  using (user_id = auth.uid());
create policy "director manages members" on school_members for all to authenticated
  using (private.has_role(school_id, '{director}')) with check (private.has_role(school_id, '{director}'));

alter table teachers enable row level security;
create policy "director manages teachers" on teachers for all to authenticated
  using (private.has_role(school_id, '{director}')) with check (private.has_role(school_id, '{director}'));
create policy "secretaire reads teachers" on teachers for select to authenticated
  using (private.has_role(school_id, '{secretaire}'));
create policy "teacher reads self" on teachers for select to authenticated
  using (id = private.my_teacher_id(school_id));

alter table courses enable row level security;
create policy "office manages courses" on courses for all to authenticated
  using (private.has_role(school_id, '{director,secretaire}')) with check (private.has_role(school_id, '{director,secretaire}'));
create policy "teacher reads courses" on courses for select to authenticated
  using (private.has_role(school_id, '{teacher}'));

alter table groups enable row level security;
create policy "office manages groups" on groups for all to authenticated
  using (private.has_role(school_id, '{director,secretaire}')) with check (private.has_role(school_id, '{director,secretaire}'));
create policy "teacher reads own groups" on groups for select to authenticated
  using (teacher_id = private.my_teacher_id(school_id));

do $$
declare t text;
begin
  foreach t in array array['students','group_students','enrollments','payments','attendance','student_documents','student_notes'] loop
    execute format('alter table %I enable row level security', t);
    execute format($p$create policy "office manages %s" on %I for all to authenticated
      using (private.has_role(school_id, '{director,secretaire}')) with check (private.has_role(school_id, '{director,secretaire}'))$p$, t, t);
  end loop;
end $$;
