-- FormaPlus schema. Amounts are whole dinars (DA).
-- Balances and payment status are derived (see enrollment_balances), never stored.

create table courses (
  id bigint generated by default as identity primary key,
  name text not null unique,
  short_name text not null,
  duration text not null,
  price integer not null check (price >= 0),
  color text not null default '#5B8DEF',
  created_at timestamptz not null default now()
);

create table teachers (
  id bigint generated by default as identity primary key,
  full_name text not null,
  subject text,
  phone text,
  email text,
  hourly_rate integer not null default 2000 check (hourly_rate >= 0),
  contract text not null default 'Temps partiel' check (contract in ('Temps plein', 'Temps partiel', 'Vacataire')),
  color text not null default '#5B8DEF',
  created_at timestamptz not null default now()
);

create table groups (
  id bigint generated by default as identity primary key,
  name text not null,
  course_id bigint references courses(id) on delete set null,
  teacher_id bigint references teachers(id) on delete set null,
  room text,
  schedule text,
  days text[] not null default '{}',
  start_time time,
  capacity integer not null default 15 check (capacity > 0),
  status text not null default 'Ouvert' check (status in ('Ouvert', 'Complet', 'Annulé')),
  color text not null default '#5B8DEF',
  created_at timestamptz not null default now()
);

create table students (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null,
  email text,
  address text,
  dob date,
  source text,
  stage text not null default 'inscrit' check (stage in ('inscrit', 'encours', 'diplome', 'abandonne')),
  staff text,
  last_contact date,
  created_at timestamptz not null default now()
);

create table group_students (
  group_id bigint not null references groups(id) on delete cascade,
  student_id bigint not null references students(id) on delete cascade,
  primary key (group_id, student_id)
);

create table enrollments (
  id bigint generated by default as identity primary key,
  student_id bigint not null references students(id) on delete cascade,
  course_id bigint not null references courses(id),
  group_id bigint references groups(id) on delete set null,
  enrolled_on date not null default current_date,
  status text not null default 'Inscrit' check (status in ('Inscrit', 'En cours', 'Terminé', 'Abandonné')),
  total integer not null check (total >= 0),
  notes text,
  created_at timestamptz not null default now()
);

create table payments (
  id bigint generated by default as identity primary key,
  enrollment_id bigint not null references enrollments(id) on delete cascade,
  amount integer not null check (amount > 0),
  paid_on date not null default current_date,
  method text not null check (method in ('Virement', 'Espèces', 'Chèque')),
  created_at timestamptz not null default now()
);

create table attendance (
  group_id bigint not null references groups(id) on delete cascade,
  student_id bigint not null references students(id) on delete cascade,
  session_date date not null,
  status text not null check (status in ('P', 'A', 'L')),
  primary key (group_id, student_id, session_date)
);

create table student_documents (
  id bigint generated by default as identity primary key,
  student_id bigint not null references students(id) on delete cascade,
  type text not null,
  file_path text not null,
  status text not null default 'À vérifier' check (status in ('Validé', 'À vérifier')),
  created_at timestamptz not null default now()
);

create table student_notes (
  id bigint generated by default as identity primary key,
  student_id bigint not null references students(id) on delete cascade,
  body text not null check (length(trim(body)) > 0),
  author_id uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index on enrollments (student_id);
create index on payments (enrollment_id);
create index on attendance (student_id);
create index on student_documents (student_id);
create index on student_notes (student_id);

create view enrollment_balances with (security_invoker = true) as
select
  e.id as enrollment_id,
  e.student_id,
  e.course_id,
  e.total,
  coalesce(sum(p.amount), 0)::integer as paid,
  greatest(e.total - coalesce(sum(p.amount), 0), 0)::integer as balance,
  case when coalesce(sum(p.amount), 0) >= e.total then 'Payé' else 'Partiel' end as payment_status
from enrollments e
left join payments p on p.enrollment_id = e.id
group by e.id;

-- Student data is personal: only signed-in staff can read or write it. The anon key alone sees nothing.
-- ponytail: every signed-in user has full access; add per-role policies when roles (formateur, secrétaire) matter.
do $$
declare t text;
begin
  foreach t in array array['courses','teachers','groups','students','group_students','enrollments','payments','attendance','student_documents','student_notes'] loop
    execute format('alter table %I enable row level security', t);
    execute format('create policy "staff full access" on %I for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;
